export default Object.freeze({
	AUTHENTICATE: 'AUTHENTICATE',
	AUTHENTICATE_ONSUCCESS: 'AUTHENTICATE_ONSUCCESS',
	AUTHENTICATE_ONFAIL: 'AUTHENTICATE_ONFAIL',

	LOGIN: 'LOGIN',
	LOGIN_ONSUCCESS: 'LOGIN_ONSUCCESS',
	LOGIN_ONFAIL: 'LOGIN_ONFAIL',

	REGISTER: 'REGISTER',
	REGISTER_ONSUCCESS: 'REGISTER_ONSUCCESS',
	REGISTER_ONFAIL: 'REGISTER_ONFAIL',

	LOGOUT: 'LOGOUT',
	LOGOUT_ONSUCCESS: 'LOGOUT_ONSUCCESS',
	LOGOUT_ONFAIL: 'LOGOUT_ONFAIL',
});
