export default Object.freeze({
	SEARCH_TASKS: 'SEARCH_TASKS',

	FETCH_TASKS: 'FETCH_TASKS',
	FETCH_TASKS_ONSUCCESS: 'FETCH_TASKS_ONSUCCESS',
	FETCH_TASKS_ONFAIL: 'FETCH_TASKS_ONFAIL',

	UPDATE_TASK: 'UPDATE_TASK',
	UPDATE_TASK_ONSUCCESS: 'UPDATE_TASK_ONSUCCESS',
	UPDATE_TASK_ONFAIL: 'UPDATE_TASK_ONFAIL',

	COMPLETE_TASK: 'COMPLETE_TASK',
	COMPLETE_TASK_ONSUCCESS: 'COMPLETE_TASK_ONSUCCESS',
	COMPLETE_TASK_ONFAIL: 'COMPLETE_TASK_ONFAIL',

	EDIT_TASK: 'EDIT_TASK',
	EDIT_TASK_ONSUCCESS: 'EDIT_TASK_ONSUCCESS',
	EDIT_TASK_ONFAIL: 'EDIT_TASK_ONFAIL',

	CREATE_TASK: 'CREATE_TASK',
	CREATE_TASK_ONSUCCESS: 'CREATE_TASK_ONSUCCESS',
	CREATE_TASK_ONFAIL: 'CREATE_TASK_ONFAIL',

	DELETE_TASK: 'DELETE_TASK',
	DELETE_TASK_ONSUCCESS: 'DELETE_TASK_ONSUCCESS',
	DELETE_TASK_ONFAIL: 'DELETE_TASK_ONFAIL',
});
